import type { Linter } from 'eslint';

const readonly = 'readonly' as const;

export const reactNativeGlobals: Linter.Globals = {
  __DEV__: readonly,
  AbortController: readonly,
  AbortSignal: readonly,
  alert: readonly,
  Blob: readonly,
  cancelAnimationFrame: readonly,
  cancelIdleCallback: readonly,
  clearImmediate: readonly,
  clearInterval: readonly,
  clearTimeout: readonly,
  console: readonly,
  fetch: readonly,
  File: readonly,
  FileReader: readonly,
  FormData: readonly,
  global: readonly,
  Headers: readonly,
  navigator: readonly,
  performance: readonly,
  process: readonly,
  queueMicrotask: readonly,
  Request: readonly,
  requestAnimationFrame: readonly,
  requestIdleCallback: readonly,
  require: readonly,
  Response: readonly,
  setImmediate: readonly,
  setInterval: readonly,
  setTimeout: readonly,
  URL: readonly,
  URLSearchParams: readonly,
  WebSocket: readonly,
  window: readonly,
  XMLHttpRequest: readonly,
};
